import type { Lang } from "../components/language";

export type ProductMultilingual = {
  name: { en: string; zh: string };
  category: { en: string; zh: string };
  footprint: { en: string; zh: string };
  height: { en: string; zh: string };
  riders: string;
  status: "New" | "Used";
  year?: string;
  badge?: string;
  image?: string;
};

export const productsMultilingual: ProductMultilingual[] = [
  {
    name: { en: "Nuclear energy crisis", zh: "核能危机" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D12M*H5.9M (Including Fence)", zh: "直径12M*高5.9M (含围栏)" },
    height: { en: "5.9 m", zh: "5.9米" },
    riders: "36",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 0.jpeg",
  },
  {
    name: { en: "Energy Plan", zh: "能源计划" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L16M*W10.5M*H11M () (Including Fence)", zh: "长16M*宽10.5M*高11M (含围栏)" },
    height: { en: "11 m", zh: "11米" },
    riders: "30",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 1.jpeg",
  },
  {
    name: { en: "Star Nuclear Guard", zh: "星核护卫队" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D14M*H4.6M() (Including Fence)", zh: "直径14M*高4.6M(含围栏)" },
    height: { en: "4.6 m", zh: "4.6米" },
    riders: "24",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 10.jpeg",
  },
  {
    name: { en: "Meow Nuclear Team", zh: "喵核战队" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D8M*H4.9M () (Including Fence)", zh: "直径8M*高4.9M (含围栏)" },
    height: { en: "4.9 m", zh: "4.9米" },
    riders: "12",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 11.jpeg",
  },
  {
    name: { en: "SPATIOTEMPORAL EDDY CURRENT", zh: "时空涡流" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "12.44M*10.34M*6.3M", zh: "12.44M*10.34M*6.3M" },
    height: { en: "N/A", zh: "N/A" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 12.jpeg",
  },
  {
    name: { en: "Stellar core ripples", zh: "星核涟漪" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L6.82M*W4.2M*H6.2M () (Including Fence)", zh: "长6.82M*宽4.2M*高6.2M (含围栏)" },
    height: { en: "6.2 m", zh: "6.2米" },
    riders: "20",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 13.jpeg",
  },
  {
    name: { en: "Star Nucleus Explorer", zh: "星核探险家" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "Diameter:10M*Height:6.3M (Including Fence)", zh: "直径:10M*高6.3M (含围栏)" },
    height: { en: "6.3 m", zh: "6.3米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 14.jpeg",
  },
  {
    name: { en: "Meow Nuclear Team", zh: "星核旋转木马" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D6.6M*H5.7M() (Including Fence)", zh: "直径6.6M*高5.7M(含围栏)" },
    height: { en: "5.7 m", zh: "5.7米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 15.jpeg",
  },
  {
    name: { en: "银河大碰撞", zh: "银河大碰撞" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L 1.5M*W 0.9M*H 0.7M", zh: "长 1.5M*宽 0.9M*高 0.7M" },
    height: { en: "0.7 m", zh: "0.7米" },
    riders: "150",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 16.jpeg",
  },
  {
    name: { en: "Meow Nuclear Team", zh: "猫核风暴" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D7M*H6M() (Including Fence)", zh: "直径7M*高6M(含围栏)" },
    height: { en: "6 m", zh: "6米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 17.jpeg",
  },
  {
    name: { en: "Super warrior", zh: "超能战士" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D9M*H6.3M () (Including Fence)", zh: "直径9M*高6.3M (包含围栏)" },
    height: { en: "6.3 m", zh: "6.3米" },
    riders: "12",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 18.jpeg",
  },
  {
    name: { en: "Star core jumping bed", zh: "星核蹦乐床" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L7M*W6M*H5.6M (L7M*W6M*H5.6M)", zh: "长7M*宽6M*高5.6M (L7M*W6M*H5.6M)" },
    height: { en: "5.6 m", zh: "5.6米" },
    riders: "6",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 19.jpeg",
  },
  {
    name: { en: "Future Engine", zh: "未来引擎" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L15M*W10M (Including Fence)", zh: "长15M*宽10M (含围栏)" },
    height: { en: "N/A", zh: "N/A" },
    riders: "12",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 2.jpeg",
  },
  {
    name: { en: "Rotating matrix", zh: "旋转矩阵" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D9M*H6.7M () (Including Fence)", zh: "直径9M*高6.7M (含围栏)" },
    height: { en: "6.7 m", zh: "6.7米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 20.jpeg",
  },
  {
    name: { en: "MEOW NUCLEAR MECHA CAR", zh: "喵核机甲车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L1.6M*W1.2M*H2.3M", zh: "长1.6M*宽1.2M*高2.3M" },
    height: { en: "2.3 m", zh: "2.3米" },
    riders: "12",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 21.jpeg",
  },
  {
    name: { en: "MEOW NUCLEAR MECHA CAR", zh: "喵核机甲车 MEOW NUCLEAR MECHA CAR" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L1.6M*W1.2M*H2.3M", zh: "长1.6M*宽1.2M*高2.3M" },
    height: { en: "2.3 m", zh: "2.3米" },
    riders: "1",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 22.jpeg",
  },
  {
    name: { en: "Meow Core Train", zh: "喵核小火车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L12M*W1.2M*H1.4M-1.6M (Size: L12M*W1.2M*H1.4-1.6M)", zh: "长12M*宽1.2M*高1.4M-1.6M (Size: L12M*W1.2M*H1.4-1.6M)" },
    height: { en: "1.4 m", zh: "1.4米" },
    riders: "11",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 23.jpeg",
  },
  {
    name: { en: "MEOW CORE TRAIN", zh: "喵核小火车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L12M*W1.2M*H1.4M-1.6M", zh: "长12M*宽1.2M*高1.4M-1.6M" },
    height: { en: "1.4 m", zh: "1.4米" },
    riders: "11",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 24.jpeg",
  },
  {
    name: { en: "Cat-core bumper cars", zh: "Cat-core bumper cars" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "1.7M*1.1M*0.95M", zh: "1.7M*1.1M*0.95M" },
    height: { en: "N/A", zh: "N/A" },
    riders: "2",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 25.jpeg",
  },
  {
    name: { en: "Cobra bumper cars", zh: "Cobra bumper cars" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L1.8M*W1.1M*H1.72M", zh: "长1.8M*宽1.1M*高1.72M" },
    height: { en: "1.72 m", zh: "1.72米" },
    riders: "2",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 26.jpeg",
  },
  {
    name: { en: "Alien Invasion", zh: "Alien Invasion" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D11M*H4.8M() (Including Fence)", zh: "直径11M*高4.8M(含围栏)" },
    height: { en: "4.8 m", zh: "4.8米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 3.jpeg",
  },
  {
    name: { en: "Measure bullets and jump", zh: "量子弹跳" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D8.6M*H6.1M (Including Fence)", zh: "直径8.6M*高6.1M (含围栏)" },
    height: { en: "6.1 m", zh: "6.1米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 4.jpeg",
  },
  {
    name: { en: "Play with the pendulum", zh: "玩转钟摆" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L8M*W7M*H6M (Including Fence)", zh: "长8M*宽7M*高6M (含围栏)" },
    height: { en: "6 m", zh: "6米" },
    riders: "20",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 5.jpeg",
  },
  {
    name: { en: "CrossFire", zh: "穿越火线" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L:9.75M*W4M*H6.85M (Including Fence)", zh: "长9.75 M*宽4M*高6.85 M (含围栏)" },
    height: { en: "6.85 m", zh: "6.85米" },
    riders: "24",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 6.jpeg",
  },
  {
    name: { en: "Nuclear Disco", zh: "核能迪斯科" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D9.1M*H7.3M () (Including Fence)", zh: "直径9.1M*高7.3M (含围栏)" },
    height: { en: "7.3 m", zh: "7.3米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 7.jpeg",
  },
  {
    name: { en: "RoboCop", zh: "星际迷航" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L7.84M*W6.6M*H3.8M (Including Fence)", zh: "长7.84M*宽6.6M*高3.8M (含围栏)" },
    height: { en: "3.8 m", zh: "3.8米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 8.jpeg",
  },
  {
    name: { en: "Catnip Knight", zh: "喵核骑士" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D10.1M*H7.5M () (Including Fence)", zh: "直径10.1M*高7.5M (含围栏)" },
    height: { en: "7.5 m", zh: "7.5米" },
    riders: "20",
    status: "New",
    image: "/products/米盈游乐设备产品介绍 conv 9.jpeg",
  },
  {
    name: { en: "Nuclear Energy Crisis Flying Chair", zh: "核能危机 空中飞椅" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D12M*H5.9M (Including Fence)", zh: "直径12M*高5.9M (含围栏)" },
    height: { en: "5.9 m", zh: "5.9米" },
    riders: "36",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 0.jpeg",
  },
  {
    name: { en: "MOUNTAINEER", zh: "爬山车 MOUNTAINEER" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L16M*W10.5M*H11M (Including Fence)", zh: "长16M*宽10.5M*高11M (含围栏)" },
    height: { en: "11 m", zh: "11米" },
    riders: "30",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 1.jpeg",
  },
  {
    name: { en: "The Great Collision of Galaxies", zh: "银河大碰撞- 碰碰车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L 1.5M x W 0.9M x H 0.7M", zh: "长 1.5M x 宽 0.9M x 高 0.7M" },
    height: { en: "0.7 m", zh: "0.7米" },
    riders: "150",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 10.jpeg",
  },
  {
    name: { en: "SPATIOTEMPORAL EDDY CURRENT", zh: "时空涡流" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L12.44M*W10.34M*H6.3M", zh: "长12.44M*宽10.34M*高6.3M" },
    height: { en: "6.3 m", zh: "6.3米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 11.jpeg",
  },
  {
    name: { en: "GLOBAL SPACE", zh: "太空环球记 GLOBAL SPACE" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D7M*H6M () (Including Fence)", zh: "直径7M*高6M (含围栏)" },
    height: { en: "6 m", zh: "6米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 12.jpeg",
  },
  {
    name: { en: "INTERSTELLAR MADNESS STATION", zh: "星际疯狂站)" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D8M*H4.5M (D8M*H4.5M)", zh: "直径8M*高4.5M (D8M*H4.5M)" },
    height: { en: "4.5 m", zh: "4.5米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 13.jpeg",
  },
  {
    name: { en: "MEOW NUCLEAR MECHA CAR", zh: "喵核机甲车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L1.6M*W1.2M*H2.3M", zh: "长1.6M*宽1.2M*高2.3M" },
    height: { en: "2.3 m", zh: "2.3米" },
    riders: "1",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 14.jpeg",
  },
  {
    name: { en: "MEOW NUCLEAR MECHA CAR", zh: "喵核机甲车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L1.6M*W1.2M*H2.3M (L1.6M*W1.2M*H2.3M)", zh: "长1.6M*宽1.2M*高2.3M (L1.6M*W1.2M*H2.3M)" },
    height: { en: "2.3 m", zh: "2.3米" },
    riders: "1",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 15.jpeg",
  },
  {
    name: { en: "MEOW CORE TRAIN", zh: "喵核小火车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L12M*W1.2M*H1.4-1.6M", zh: "长12M*宽1.2M*高1.4-1.6M" },
    height: { en: "N/A", zh: "N/A" },
    riders: "11",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 16.jpeg",
  },
  {
    name: { en: "MEOW CORE TRAIN", zh: "喵核小火车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L12M*W1.2M*H1.4-1.6M", zh: "长12M*宽1.2M*高1.4-1.6M" },
    height: { en: "N/A", zh: "N/A" },
    riders: "11",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 17.jpeg",
  },
  {
    name: { en: "POSEIDON", zh: "海神号 POSEIDON" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L15M*W10M*H6M", zh: "长15M*宽10M*高6M" },
    height: { en: "6 m", zh: "6米" },
    riders: "24",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 18.jpeg",
  },
  {
    name: { en: "INTERSTELLAR", zh: "穿越时空 INTERSTELLAR" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L15M*W10M*H6M (L15M*W10M*H6M), H:1.98M (Equipment Operating Height: 1.98M)", zh: "长15M*宽10M*高6M (L15M*W10M*H6M), 设备运行高度:1.98M (Equipment Operating Height: 1.98M)" },
    height: { en: "6 m", zh: "6米" },
    riders: "18",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 19.jpeg",
  },
  {
    name: { en: "Measure bullets and jump", zh: "量子弹跳" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D8.6M*H6.1M () (Including Fence)", zh: "直径8.6M*高6.1M (含围栏)" },
    height: { en: "6.1 m", zh: "6.1米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 2.jpeg",
  },
  {
    name: { en: "LUCKY CAROUSEL", zh: "幸运转马" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D8M*H6.3M (Including Fence)", zh: "直径8M*高6.3M (含围栏)" },
    height: { en: "6.3 m", zh: "6.3米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 20.jpeg",
  },
  {
    name: { en: "ROMANTIC CAROUSEL", zh: "浪漫拾光转马" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D8M*H6.3M (Including Fence)", zh: "直径8M*高6.3M (含围栏)" },
    height: { en: "6.3 m", zh: "6.3米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 21.jpeg",
  },
  {
    name: { en: "Astronaut Self-Control Aircraft", zh: "宇航员自控飞机" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D8M*H4.9M (Including Fence)", zh: "直径8M*高4.9M (含围栏)" },
    height: { en: "4.9 m", zh: "4.9米" },
    riders: "12",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 22.jpeg",
  },
  {
    name: { en: "MOE DUCK LAND", zh: "萌鸭乐园" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L15M*W8.5M () (Including Fence)", zh: "长15M*宽8.5M (含围栏)" },
    height: { en: "N/A", zh: "N/A" },
    riders: "12",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 23.jpeg",
  },
  {
    name: { en: "PET WARS CLIMBING CAR", zh: "宠物作战儿童爬山车)" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L16M*W10M (Including Fence)", zh: "长16M*宽10M (含围栏)" },
    height: { en: "N/A", zh: "N/A" },
    riders: "30",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 24.jpeg",
  },
  {
    name: { en: "MAGIC CASTLE WATER RAFTING", zh: "童话城堡水道漂流" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L150M*W50M*H0.9M (L150M*W50M*H0.9M)", zh: "长150M*宽50M*高0.9M (L150M*W50M*H0.9M)" },
    height: { en: "0.9 m", zh: "0.9米" },
    riders: "N/A",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 25.jpeg",
  },
  {
    name: { en: "FANTASY STAR INTERNET CELEBRITY SWING", zh: "梦幻星网红秋千" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L8M*W7M*H6M (Including Fence)", zh: "长8M*宽7M*高6M (含围栏)" },
    height: { en: "6 m", zh: "6米" },
    riders: "20",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 26.jpeg",
  },
  {
    name: { en: "OFF ROAD VEHICLE", zh: "越野战车 OFF-ROAD VEHICLE" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D10M*H5.5M (Including Fence)", zh: "直径10M*高5.5M (含围栏)" },
    height: { en: "5.5 m", zh: "5.5米" },
    riders: "24",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 27.jpeg",
  },
  {
    name: { en: "Spinning Ferris Wheel", zh: "旋转飞椅" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D8M*H7.2M () (Including Fence)", zh: "直径8M*高7.2M (含围栏)" },
    height: { en: "7.2 m", zh: "7.2米" },
    riders: "24",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 28.jpeg",
  },
  {
    name: { en: "MOE DUCK LAND", zh: "喷球车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D7M*H6M (Including Fence)", zh: "直径7M*高6M (含围栏)" },
    height: { en: "6 m", zh: "6米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 29.jpeg",
  },
  {
    name: { en: "Rotating matrix", zh: "旋转矩阵" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D9M*H6.7M (Including Fence)", zh: "直径9M*高6.7M (含围栏)" },
    height: { en: "6.7 m", zh: "6.7米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 3.jpeg",
  },
  {
    name: { en: "GLOBAL GLIDING", zh: "环球滑翔" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D10M*H6.3M (), H:1.98M (Including Fence)", zh: "直径10M*高6.3M (含围栏), 设备运行高度:1.98M" },
    height: { en: "6.3 m", zh: "6.3米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 30.jpeg",
  },
  {
    name: { en: "PIRATE SHIP", zh: "海盗船 PIRATE SHIP" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L6.5M*W4.5M*H4.5M(Including Fence)", zh: "长6.5M*宽4.5M*高4.5M(含围栏)" },
    height: { en: "4.5 m", zh: "4.5米" },
    riders: "12",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 31.jpeg",
  },
  {
    name: { en: "星际探险六人蹦床", zh: "星际探险六人蹦床" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L7M*W6M*H5.6M", zh: "长7M*宽6M*高5.6M" },
    height: { en: "5.6 m", zh: "5.6米" },
    riders: "6",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 32.jpeg",
  },
  {
    name: { en: "MAGIC CASTLE WATER RAFTING", zh: "打地鼠儿童单人蹦床" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L1.9M*W2.3M*H3.7M", zh: "长1.9M*宽2.3M*高3.7M" },
    height: { en: "3.7 m", zh: "3.7米" },
    riders: "1",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 34.jpeg",
  },
  {
    name: { en: "KUPAO GO KART", zh: "酷跑卡丁车)" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L1.35M*W0.87M*H0.83M", zh: "长1.35M*宽0.87M*高0.83M" },
    height: { en: "0.83 m", zh: "0.83米" },
    riders: "1",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 35.jpeg",
  },
  {
    name: { en: "KODUCK MINI TRAIN", zh: "哒哒鸭小火车)" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L12M*W1.2M*H1.4-1.6M", zh: "长12M*宽1.2M*高1.4-1.6M" },
    height: { en: "N/A", zh: "N/A" },
    riders: "11",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 36.jpeg",
  },
  {
    name: { en: "SPACE MINI TRAIN", zh: "太空队小火车)" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L12M*W1.2M*H1.4", zh: "长12M*宽1.2M*高1.4" },
    height: { en: "N/A", zh: "N/A" },
    riders: "11",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 37.jpeg",
  },
  {
    name: { en: "WILD DRIFT BUMPER CAR", zh: "狂飙漂移碰碰车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L 1.5M* W 0.9M* H 0.7M (L1.5M*W0.9M*H0.7M)", zh: "长 1.5M* 宽 0.9M* 高 0.7M (L1.5M*W0.9M*H0.7M)" },
    height: { en: "0.7 m", zh: "0.7米" },
    riders: "150",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 38.jpeg",
  },
  {
    name: { en: "TORNADO DRIFT BUMPER CAR", zh: "旋风漂移碰碰车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "1.5M * 0.9M * 0.7M", zh: "1.5M * 0.9M * 0.7M" },
    height: { en: "N/A", zh: "N/A" },
    riders: "150",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 39.jpeg",
  },
  {
    name: { en: "Star Nucleus Explorer", zh: "星核探险家" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D10M*H6.3M () (Including Fence)", zh: "直径10M*高6.3M (含围栏)" },
    height: { en: "6.3 m", zh: "6.3米" },
    riders: "16",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 4.jpeg",
  },
  {
    name: { en: "VICTORY DRIFT BUMPER CAR", zh: "赛赢漂移碰碰车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L 1.5M* W 0.9M* H 0.7M (L1.5M*W0.9M*H0.7M)", zh: "长 1.5M* 宽 0.9M* 高 0.7M (L1.5M*W0.9M*H0.7M)" },
    height: { en: "0.7 m", zh: "0.7米" },
    riders: "150",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 41.jpeg",
  },
  {
    name: { en: "WIND DRIVEN DRIFT COLLISION CAR", zh: "风驰漂移碰碰车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L 1.5M* W 0.9M* H 0.7M (L1.5M*W0.9M*H0.7M)", zh: "长 1.5M* 宽 0.9M* 高 0.7M (L1.5M*W0.9M*H0.7M)" },
    height: { en: "0.7 m", zh: "0.7米" },
    riders: "150",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 42.jpeg",
  },
  {
    name: { en: "MAIXUAN DRIFT COLLISION CAR", zh: "MAIXUAN DRIFT COLLISION CAR" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L1.7M*W1.1M*H0.95M", zh: "长1.7M*宽1.1M*高0.95M" },
    height: { en: "0.95 m", zh: "0.95米" },
    riders: "2",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 43.jpeg",
  },
  {
    name: { en: "TORNADO RACING CAR", zh: "旋风飞车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L1.6M*W1.1M*H0.85M", zh: "长1.6M*宽1.1M*高0.85M" },
    height: { en: "0.85 m", zh: "0.85米" },
    riders: "2",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 44.jpeg",
  },
  {
    name: { en: "Q MOE RACING CAR", zh: "萌飞车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L1.65M*W0.9M*H1.02M (L1.65M*W0.9M*H1.02M)", zh: "长1.65M*宽0.9M*高1.02M (L1.65M*W0.9M*H1.02M)" },
    height: { en: "1.02 m", zh: "1.02米" },
    riders: "2",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 45.jpeg",
  },
  {
    name: { en: "OFF ROAD TANK", zh: "越野战车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L1.8M*W1.1M*H1.72M (L1.8M*W1.1M*H1.72M)", zh: "长1.8M*宽1.1M*高1.72M (L1.8M*W1.1M*H1.72M)" },
    height: { en: "1.72 m", zh: "1.72米" },
    riders: "2",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 46.jpeg",
  },
  {
    name: { en: "SUPER RACING CAR", zh: "急速飞车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L1.7M*W1.1M*H0.95M", zh: "长1.7M*宽1.1M*高0.95M" },
    height: { en: "0.95 m", zh: "0.95米" },
    riders: "2",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 47.jpeg",
  },
  {
    name: { en: "BIG EYES RACING CAR", zh: "大眼酷飞车" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L1.7M*W1.1M*H1.08M", zh: "长1.7M*宽1.1M*高1.08M" },
    height: { en: "1.08 m", zh: "1.08米" },
    riders: "2",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 49.jpeg",
  },
  {
    name: { en: "Super warrior", zh: "超能战士" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "D9M*H6.3M () (Including Fence)", zh: "直径9M*高6.3M (含围栏)" },
    height: { en: "6.3 m", zh: "6.3米" },
    riders: "12",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 5.jpeg",
  },
  {
    name: { en: "Interstellar", zh: "穿越时空 Interstellar" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "未找到", zh: "未找到" },
    height: { en: "N/A", zh: "N/A" },
    riders: "N/A",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 51.jpeg",
  },
  {
    name: { en: "玩转钟摆", zh: "玩转钟摆" },
    category: { en: "Family Ride", zh: "家庭游乐设备" },
    footprint: { en: "L8M*W7M*H6M () (Including Fence)", zh: "长8M*宽7M*高6M (含围栏)" },
    height: { en: "6 m", zh: "6米" },
    riders: "20",
    status: "New",
    image: "/products/米盈游乐设备(1) [10-76] conv 9.jpeg",
  }
];

// Helper function to get localized product
export function getLocalizedProduct(product: ProductMultilingual, lang: Lang) {
  const isZh = lang === "zh";
  return {
    name: product.name[isZh ? "zh" : "en"] || product.name["en"],
    category: product.category[isZh ? "zh" : "en"] || product.category["en"],
    footprint: product.footprint[isZh ? "zh" : "en"] || product.footprint["en"],
    height: product.height[isZh ? "zh" : "en"] || product.height["en"],
    riders: product.riders,
    status: product.status,
    year: product.year,
    badge: product.badge,
    image: product.image,
  };
}

// Export products array for backward compatibility (defaults to English)
export const products = productsMultilingual.map(p => getLocalizedProduct(p, "en"));
